package velib.view;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import velib.model.Client;

/**
 *
 * @author Nicolas
 */

public class IdentifiantPerduPanel extends javax.swing.JPanel {

    /** Creates new form IdentifiantPerduPanel */
    public IdentifiantPerduPanel() {
        initComponents();
    }


    public void fillUpQuestionSecrete(Client client)
    {
        questionSecreteJLabel.setText(client.getUser().getQuestionSecrete());        
    }

    public void fillUpPassword(Client client)
    {
        passwordJLabel.setText(client.getUser().getPassword());
    }

    public void reponseErrorPopup()
    {
        JOptionPane.showMessageDialog(this, "Mauvaise réponse");
    }

    public void clienErrorPopup()
    {
        JOptionPane.showMessageDialog(this, "Etes vous sur d'être client ? :)");
    }

    public void addOkButtonListener(ActionListener al)
    {
        okButton.addActionListener(al);
    }

    public void addOk2ButtonListener(ActionListener al)
    {
        ok2JButton.addActionListener(al);
    }

    public JTextField getLastNameTextField() {
        return lastNameTextField;
    }

    public JTextField getFirstNameTextField1() {
        return firstNameTextField1;
    }

    public JTextField getReponseSecreteJTextField() {
        return reponseSecreteJTextField;
    }

    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        firstNameTextField1 = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        questionSecreteJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reponseSecreteJTextField = new javax.swing.JTextField();
        ok2JButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        jLabel1.setText("Veuillez saisir votre nom et prénom");

        okButton.setText("OK");

        jLabel2.setText("Veuillez saisir votre réponse secrète");

        ok2JButton.setText("OK");

        jLabel3.setText("Votre mot de passe est : ");

        passwordJLabel.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionSecreteJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(firstNameTextField1))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(okButton))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(passwordJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(reponseSecreteJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ok2JButton)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton))
                .addGap(32, 32, 32)
                .addComponent(questionSecreteJLabel)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reponseSecreteJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok2JButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordJLabel))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstNameTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton ok2JButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JLabel questionSecreteJLabel;
    private javax.swing.JTextField reponseSecreteJTextField;
    // End of variables declaration//GEN-END:variables

}
