/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AbonnementPanel.java
 *
 * Created on Mar 16, 2011, 10:48:04 PM
 */

package velib.view;

import java.awt.event.ActionListener;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import velib.model.AbonnementType;

/**
 *
 * @author andre
 */
public class AbonnementPanel extends javax.swing.JPanel {

    /** Creates new form AbonnementPanel */
    public AbonnementPanel() {
        initComponents();
    }

    // Add action listener to every buttons in the group
    public void addAbonnementGroupButtonListener(ActionListener actionListener)
    {
        Enumeration elements = buttonGroup1.getElements();

        while (elements.hasMoreElements())
        {
            AbstractButton button = (AbstractButton)elements.nextElement();
            button.addActionListener(actionListener);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        oneDay = new javax.swing.JButton();
        halfDayButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        oneWeekButton = new javax.swing.JButton();
        oneMonthButton = new javax.swing.JButton();
        oneYearButton = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Courte duree"));

        oneDay.setText("1 Journee");
        oneDay.setActionCommand(AbonnementType.ONE_DAY.value());
        buttonGroup1.add(oneDay);
        oneDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneDayActionPerformed(evt);
            }
        });

        halfDayButton.setText("1/2 Journee");
        halfDayButton.setActionCommand(AbonnementType.HALF_DAY.value());
        buttonGroup1.add(halfDayButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(halfDayButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(oneDay, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(halfDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(oneDay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Longue duree"));

        oneWeekButton.setText("1 Semaine");
        oneWeekButton.setActionCommand(AbonnementType.ONE_WEEK.value());
        buttonGroup1.add(oneWeekButton);

        oneMonthButton.setText("1 Mois");
        oneMonthButton.setActionCommand(AbonnementType.ONE_MONTH.value());
        buttonGroup1.add(oneMonthButton);
        oneMonthButton.setMaximumSize(new java.awt.Dimension(81, 23));
        oneMonthButton.setMinimumSize(new java.awt.Dimension(81, 23));

        oneYearButton.setText("1 An");
        oneYearButton.setActionCommand(AbonnementType.ONE_YEAR.value());
        buttonGroup1.add(oneYearButton);
        oneYearButton.setMaximumSize(new java.awt.Dimension(81, 23));
        oneYearButton.setMinimumSize(new java.awt.Dimension(81, 23));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(oneYearButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(oneMonthButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(oneWeekButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(oneWeekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oneMonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oneYearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void oneDayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_oneDayActionPerformed
    {//GEN-HEADEREND:event_oneDayActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_oneDayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton halfDayButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton oneDay;
    private javax.swing.JButton oneMonthButton;
    private javax.swing.JButton oneWeekButton;
    private javax.swing.JButton oneYearButton;
    // End of variables declaration//GEN-END:variables

}
