/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdministrationWindowFrame.java
 *
 * Created on 21 mars 2011, 12:45:07
 */

package velib.view;

import java.awt.event.ActionListener;

/**
 *
 * @author Nicolas
 */
public class AdministrationWindowFrame extends javax.swing.JFrame
{

    /** Creates new form AdministrationWindowFrame */
    public AdministrationWindowFrame()
    {
        initComponents();
    }

    public void addEditDatabaseButtonListener(ActionListener al)
    {
        editDatabaseButton.addActionListener(al);
    }

    public void addGeneralManagementButtonListener(ActionListener al)
    {
        generalManagementButton.addActionListener(al);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editDatabaseButton = new javax.swing.JButton();
        generalManagementButton = new javax.swing.JButton();
        usersListButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editDatabaseButton.setText("Edit Database");

        generalManagementButton.setText("General Management");

        usersListButton.setText("Liste utilisateurs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(usersListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editDatabaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generalManagementButton))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(editDatabaseButton)
                .addGap(18, 18, 18)
                .addComponent(generalManagementButton)
                .addGap(18, 18, 18)
                .addComponent(usersListButton)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrationWindowFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editDatabaseButton;
    private javax.swing.JButton generalManagementButton;
    private javax.swing.JButton usersListButton;
    // End of variables declaration//GEN-END:variables

}
