/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UsersControlFrame.java
 *
 * Created on 20 mars 2011, 12:32:17
 */

package velib.view;

import velib.dao.LocationDAO;
import velib.model.Location;
/**
 *
 * @author G
 */
public class UsersControlFrame extends javax.swing.JFrame
{
    LocationDAO locationDAO = new LocationDAO();
    private Location[] location = locationDAO.findAllLocation();

    /** Creates new form UsersControlFrame */
    public UsersControlFrame()
    {
        initComponents();
        setUpUsersControlFrame(location);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    public UsersControlFrame getUsersControlFrame()
    {
        return usersControlFrame;
    }

     // Fills the combo box with bornes objects
    private void setUpUsersControlFrame(Location[] location)
    {
        for (int i=0; i<location.length; i++)
        {
            //String nomClient = location[i].getClient().getFullName();
            //Long idVelo = location[i].getVelo().getId();
            //testComboBox.addItem(nomClient);
            System.out.println(i);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        testComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Title.setText("Liste des utilisateurs actifs");

        testComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        testComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title))
                .addContainerGap(508, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Title)
                .addGap(44, 44, 44)
                .addComponent(testComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testComboBoxActionPerformed
    {//GEN-HEADEREND:event_testComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testComboBoxActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new UsersControlFrame().setVisible(true);
            }
        });
    }

    private velib.view.UsersControlFrame usersControlFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JComboBox testComboBox;
    // End of variables declaration//GEN-END:variables

}
